=== ti360gh/Reanimator-steam/source/Mods/ModSchema.xsd
<?xml version="1.0" encoding="utf-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">

  <xs:element name="title" type="xs:string"/>
  <xs:element name="version" type="xs:string"/>
  <xs:element name="description" type="xs:string"/>
  <xs:element name="url" type="xs:string"/>
  <xs:element name="append" type="xs:string"/>
  <xs:element name="integer" type="xs:integer"/>
  <xs:element name="float" type="xs:float"/>
  <xs:element name="string" type="xs:string"/>
  

  <xs:attribute name="id" type="xs:string"/>
  <xs:attribute name="value" type="xs:integer"/>
  
  <xs:element name="type">
    <xs:simpleType>
      <xs:restriction base="xs:string">
        <xs:enumeration value="required"/>
        <xs:enumeration value="optional"/>
      </xs:restriction>
    </xs:simpleType>
  </xs:element>

  <xs:element name="replace">
    <xs:complexType>
      <xs:group ref="data_type"/>
    </xs:complexType>
  </xs:element>

  <xs:element name="divide">
    <xs:complexType>
      <xs:group ref="data_type"/>
    </xs:complexType>
  </xs:element>

  <xs:group name="data_type">
    <xs:choice>
      <xs:element ref="integer"/>
      <xs:element ref="float"/>
      <xs:element ref="string"/>
    </xs:choice>
  </xs:group>
  
  <xs:element name="bitwise">
    <xs:complexType>
      <xs:sequence>
        <xs:element name="switch" minOccurs="1" maxOccurs="1">
          <xs:simpleType>
            <xs:restriction base="xs:boolean"/>
          </xs:simpleType>
        </xs:element>
      </xs:sequence>
      <xs:attribute ref="id" use="required"/>
    </xs:complexType>
  </xs:element>

  <xs:group name="attribute_modify">
    <xs:choice>
      <xs:element ref="bitwise" maxOccurs="unbounded"/>
      <xs:element ref="replace"/>
      <xs:element ref="divide"/>
    </xs:choice>
  </xs:group>
  
  <xs:element name="attribute">
    <xs:annotation>
      <xs:documentation>Specify the attribute to modify.</xs:documentation>
    </xs:annotation>
    <xs:complexType>
      <xs:group ref="attribute_modify"/>
      <xs:attribute ref="id" use="required"/>
    </xs:complexType>
  </xs:element>
  
  <xs:element name="entity">
    <xs:annotation>
      <xs:documentation>Indentity the entity and which attributes to modify.</xs:documentation>
    </xs:annotation>
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="attribute" maxOccurs="unbounded"/>
      </xs:sequence>
      <xs:attribute ref="id" use="required"/>
      <xs:attribute ref="value" use="optional"/>
    </xs:complexType>
  </xs:element>
  
  <xs:element name="modify">
    <xs:annotation>
      <xs:documentation>Specifies which entities you want to modify.</xs:documentation>
    </xs:annotation>
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="entity" maxOccurs="unbounded"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>

  <xs:group name="edit">
    <xs:annotation>
      <xs:documentation>HGL files can either be modified and/or appended to (eventually).</xs:documentation>
    </xs:annotation>
    <xs:sequence>
      <xs:element ref="append" minOccurs="0"/>
      <xs:element ref="modify" minOccurs="0"/>
    </xs:sequence>
  </xs:group>

  <xs:element name="file">
    <xs:annotation>
      <xs:documentation>The file can either be replaced (specifying a path) or edited using XML syntax.</xs:documentation>
    </xs:annotation>
    <xs:complexType>
      <xs:choice>
        <xs:element ref="replace"/>
        <xs:group ref="edit"/>
      </xs:choice>
      <xs:attribute ref="id" use="required"/>
    </xs:complexType>
  </xs:element>

  <xs:element name="pack">
    <xs:annotation>
      <xs:documentation>Specify which pack you want to edit, usually this will only be the latest patch pack.</xs:documentation>
    </xs:annotation>
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="file" maxOccurs="unbounded"/>
      </xs:sequence>
      <xs:attribute ref="id" use="required"/>
    </xs:complexType>
  </xs:element>
  
  <xs:element name="modification">
    <xs:annotation>
      <xs:documentation>Describes the details of the modification.</xs:documentation>
    </xs:annotation>
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="title" maxOccurs="1"/>
        <xs:element ref="version" minOccurs="0" maxOccurs="1"/>
        <xs:element ref="description" minOccurs="0" maxOccurs="1"/>
        <xs:element ref="url" minOccurs="0" maxOccurs="1"/>
        <xs:element ref="type" minOccurs="0" maxOccurs="1"/>
        <xs:element ref="pack"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>

  <xs:element name="revival">
    <xs:annotation>
      <xs:appinfo>Revival Modifications</xs:appinfo>
      <xs:documentation xml:lang="en">This is the base level of a Revival modification.</xs:documentation>
    </xs:annotation>
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="modification" maxOccurs="unbounded"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>

</xs:schema>

=== ti360gh/Reanimator-steam/source/Mods/RevivalMod.xml
<?xml version="1.0" encoding="utf-8" ?>
<revival xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="ModSchema.xsd">
  <modification>
    <title>Revival SP modification</title>
    <version>2.0</version>
    <description>This is the base SP modification developed by the Revival team.</description>
    <url>http://www.hellgateaus.net</url>
    <type>required</type>
    <pack id="Default">
      <!--<file id="Game_Globals">
        <modify>
          <entity id="MaxLuckTugboat" value="55">
            <attribute id="IntValue">
              <replace>
                <integer>10000</integer>
              </replace>
            </attribute>
          </entity>
        </modify>
      </file>
      <file id="Item_Levels">
        <modify>
          <entity id="*">
            <attribute id="AugmentCostRare">
              <divide>
                <integer>2</integer>
              </divide>
            </attribute>
            <attribute id="AugmentCostLegendary">
              <divide>
                <integer>2</integer>
              </divide>
            </attribute>
          </entity>
        </modify>
      </file>-->
      <file id="Item_Quality">
        <modify>
          <entity id="Legendary" value="3">
            <attribute id="VendorRarity">
              <replace>
                <integer>4</integer>
              </replace>
            </attribute>
          </entity>
          <entity id="Mutant" value="4">
            <attribute id="ExtraScrapQuality">
              <replace>
                <integer>4</integer>
              </replace>
            </attribute>
          </entity>
          <entity id="Unique" value="5">
            <attribute id="VendorRarity">
              <replace>
                <integer>1</integer>
              </replace>
            </attribute>
            <attribute id="Price_Multiplier">
              <replace>
                <integer>21</integer>
              </replace>
            </attribute>
          </entity>
        </modify>
      </file>
      <!--<file id="Items">
        <modify>
          <entity id="SkillRetrainer" value="15">
            <attribute id="Quality">
              <replace>
                <integer>5</integer>
              </replace>
            </attribute>
          </entity>
        </modify>
      </file>-->
    </pack>
  </modification>
  <modification>
    <title>Elite for normal mode</title>
    <version>2.0</version>
    <description>Reduces elite mode characters difficulty to normal mode, while benefiting from additional multipliers.</description>
    <url>http://www.hellgateaus.net</url>
    <type>optional</type>
    <pack id="Default">
      <file id="Game_Globals">
        <modify>
          <entity id="EliteMonsterDamagePercent">
            <attribute id="FloatValue">
              <replace>
                <float>0</float>
              </replace>
            </attribute>
          </entity>
          <entity id="EliteMonsterSFXChancePercent">
            <attribute id="FloatValue">
              <replace>
                <float>0</float>
              </replace>
            </attribute>
          </entity>
          <entity id="ElitePlayerDamagePercent">
            <attribute id="FloatValue">
              <replace>
                <float>0</float>
              </replace>
            </attribute>
          </entity>
          <entity id="ElitePlayerSFXChancePercent">
            <attribute id="FloatValue">
              <replace>
                <float>0</float>
              </replace>
            </attribute>
          </entity>
        </modify>
      </file>
    </pack>
  </modification>
</revival>
