=== ti360gh/Reanimator-steam/source/ModSchema.xsd
<?xml version="1.0" encoding="utf-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">

<xs:element name="revival">
  <xs:complexType>
    <xs:sequence>
      <xs:element name="modification">
        <xs:complexType>
          <xs:sequence>
            <xs:element name="title" type="xs:string" minOccurs="1" maxOccurs="1"/>
            <xs:element name="description" type="xs:string" maxOccurs="1"/>
            <xs:element name="version" type="xs:string" maxOccurs="1"/>
            <xs:element name="pack">
              <xs:complexType>
                <xs:sequence>
                  <xs:element name="file" maxOccurs="unbounded">
                    <xs:complexType>
                      <xs:sequence>
                        <xs:element name="replace" minOccurs="0">
                          <xs:complexType>
                            <xs:sequence>
                              <xs:element name="path">
                                <xs:simpleType>
                                  <xs:restriction base="xs:string"/>
                                </xs:simpleType>
                              </xs:element>
                            </xs:sequence>
                          </xs:complexType>
                        </xs:element>
                        <xs:element name="modify" minOccurs="0" maxOccurs="unbounded">
                          <xs:complexType>
                            <xs:sequence>
                              <xs:element name="entity" minOccurs="1" maxOccurs="unbounded">
                                <xs:complexType>
                                  <xs:sequence>
                                    <xs:element name="attribute" minOccurs="1" maxOccurs="unbounded">
                                      <xs:complexType>
                                        <xs:sequence>
                                          <xs:element name="replace" minOccurs="0">
                                            <xs:complexType>
                                              <xs:sequence>
                                                <xs:element name="data" minOccurs="1" maxOccurs="1"/>
                                              </xs:sequence>
                                            </xs:complexType>
                                          </xs:element>
                                          <xs:element name="bitwise" minOccurs="0">
                                            <xs:complexType>
                                              <xs:sequence>
                                                <xs:element name="bit" minOccurs="1">
                                                  <xs:complexType>
                                                    <xs:sequence>
                                                      <xs:element name="flip" minOccurs="1" maxOccurs="1">
                                                        <xs:simpleType>
                                                          <xs:restriction base="xs:string">
                                                            <xs:enumeration value="no"/>
                                                            <xs:enumeration value="yes"/>
                                                          </xs:restriction>
                                                        </xs:simpleType>
                                                      </xs:element>
                                                    </xs:sequence>
                                                    <xs:attribute name="id" type="xs:string"/>
                                                  </xs:complexType>
                                                </xs:element>
                                              </xs:sequence>
                                              <xs:attribute name="id" type="xs:string"/>
                                            </xs:complexType>
                                          </xs:element>
                                        </xs:sequence>
                                        <xs:attribute name="id" type="xs:string"/>
                                      </xs:complexType>
                                    </xs:element>
                                  </xs:sequence>
                                  <xs:attribute name="id" type="xs:string"/>
                                </xs:complexType>
                              </xs:element>
                            </xs:sequence>
                          </xs:complexType>
                        </xs:element>
                      </xs:sequence>
                      <xs:attribute name="id" type="xs:string"/>
                    </xs:complexType>
                  </xs:element>
                </xs:sequence>
                <xs:attribute name="id" type="xs:string"/>
              </xs:complexType>
            </xs:element>
          </xs:sequence>
        </xs:complexType>
      </xs:element>
    </xs:sequence>
  </xs:complexType>
</xs:element>
  
</xs:schema>

=== ti360gh/Reanimator-steam/source/RevivalMod.xml
<?xml version="1.0" encoding="utf-8" ?>
<revival xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:noNamespaceSchemaLocation="ModSchema.xsd">
  <modification>
    <title>Revival SP modification</title>
    <description>This is the base SP modification developed by the Revival team.</description>
    <version>1.1.0</version>
    <pack id="hellgate000">
      <file id="gameglobals.txt.cooked">
        <replace>
          <path>./gameglobals.txt.cooked</path>
        </replace>
      </file>
      <file id="items.txt.cooked">
        <modify>
          <entity id="black_knight_dye">
            <attribute id="affix1">
              <replace>
                <data>all_attributes_3</data>
              </replace>
            </attribute>
            <attribute id="property_mask">
              <bitwise>
                <bit id="can_vendor">
                  <flip>yes</flip>
                </bit>
              </bitwise>
            </attribute>
          </entity>
        </modify>
      </file>
    </pack>
  </modification>
</revival>
